language: node_js
# language: minimal - minimal is image available in Ubuntu Focal dist: focal... It is not tailored to any particular promgramming language. It is optimized to be faster and use less disk space.

node_js:
  - 13

services:
  - docker

# Install dependencies
install:

# Scripts to be run such as tests
before_script:

script:
  - cd udagram-api-feed
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed mkortmann/udagram-api-feed

  - cd ../udagram-api-users
  - docker build -t udagram-api-users .
  - docker tag udagram-api-users mkortmann/udagram-api-users

  - cd ../udagram-frontend
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend mkortmann/udagram-frontend

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mkortmann/udagram-api-feed
  - docker push mkortmann/udagram-api-users
  - docker push mkortmann/udagram-api-frontend