# It specifies how our pods should be created!
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
        api: external
    spec:
      containers:
      - name: udagram-frontend
        image: mkortmann/udagram-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
      restartPolicy: Always
