
# config data for the compose
version: '3.9'
services:
  udagram-api-feed:

    image: mkortmann/udagram-api-feed
    environment:
      POSTGRES_USERNAME=$POSTGRES_USERNAME
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      POSTGRES_HOST=$POSTGRES_HOST
      POSTGRES_DATABASE=$POSTGRES_DATABASE
      AWS_MEDIA_BUCKET=$AWS_MEDIA_BUCKET
      AWS_REGION=$AWS_REGION
      AWS_PROFILE=$AWS_PROFILE
      JWT_SECRET=$JWT_SECRET
      URL=$URL
  udagram-api-users:
    image: mkortmann/udagram-api-feed
    environment:
      POSTGRES_USERNAME=$POSTGRES_USERNAME
      POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      POSTGRES_HOST=$POSTGRES_HOST
      POSTGRES_DATABASE=$POSTGRES_DATABASE
      AWS_MEDIA_BUCKET=$AWS_MEDIA_BUCKET
      AWS_REGION=$AWS_REGION
      AWS_PROFILE=$AWS_PROFILE
      JWT_SECRET=$JWT_SECRET
      URL=$URL
  udagram-frontend:
    image: mkortmann/udagram-frontend
  udagram-reversyproxy:
    image: mkortmann/udagram-reversyproxy
    ports:
      - 8080:8080


