# file is used to specify how our pods are exposed
apiVersion: v1
kind: Service
metadata:
  name: udagram-users
  labels:
    service: udagram-users
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-users

