# file is used to specify how our pods are exposed
apiVersion: v1
# It is a service!!!
kind: Service
metadata:
  name: udagram-feed
  labels:
    service: udagram-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-feed

