
# It specifies how our pods should be created!
apiVersion: apps/v1
# specify is a deployment.yaml file
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    service: udagram-api-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udagram-api-feed
  template:
    metadata:
      labels:
        service: udagram-api-feed
# tell which docker image to use
    spec:
      containers:
      - name: udagram-api-feed
        image: mkortmann/udagram-api-feed:latest
        resources:
          requests:
            memory: "1024Mi"
            cpu: "250m"
          limits:
            memory: "2048Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: POSTGRES_DB
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: AWS_BUCKET
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: AWS_REGION
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: AWS_PROFILE
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: URL
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: JWT_SECRET
      restartPolicy: Always